services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./egedoma:/egedoma
    environment:
      - SECRET_KEY=django-insecure-3u2b)muu!azt-!*_y+t82&@w28rih%8h3#4hq!7q76m2j%1!pj
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:15.1-alpine3.17
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./egedoma:/egedoma
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./egedoma:/egedoma
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"