# Generated by Django 4.1.5 on 2023-01-11 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authhash',
            options={'verbose_name_plural': 'auth hashes'},
        ),
        migrations.AddField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 14, 23, 24, 469362, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='authhash',
            name='expired',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
