# Generated by Django 4.1.5 on 2023-01-11 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_authhash_options_authhash_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authhash',
            old_name='expired',
            new_name='is_expired',
        ),
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 11, 9, 957614, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
