# Generated by Django 4.1.5 on 2023-01-13 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_created_alter_authhash_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 22, 59, 8, 291025, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 22, 59, 8, 289393, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
