# Generated by Django 4.1.5 on 2023-01-11 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_expired_authhash_is_expired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 57, 5, 396744, tzinfo=datetime.timezone.utc), editable=False)),
                ('firstname', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('photo', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 57, 5, 396153, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
