# Generated by Django 4.1.5 on 2023-01-11 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_alter_authhash_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 59, 22, 609458, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 59, 22, 610797, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank='', max_length=64, null=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(blank='', max_length=128, null=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank='', max_length=64, null=''),
        ),
    ]
