# Generated by Django 4.1.5 on 2023-01-11 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_is_active_alter_authhash_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 59, 27, 817091, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 59, 27, 817735, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
