# Generated by Django 4.1.5 on 2023-01-14 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_authhash_created_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authhash',
            name='created',
        ),
        migrations.AddField(
            model_name='authhash',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 0, 5, 10, 892513, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 0, 5, 10, 890778, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
