# Generated by Django 4.1.5 on 2023-01-11 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_authhash_created_alter_student_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 16, 1, 40, 180911, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 16, 1, 40, 181625, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
