# Generated by Django 4.1.5 on 2023-01-11 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_authhash_created_alter_student_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 16, 3, 20, 162892, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 16, 3, 20, 163649, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
