# Generated by Django 4.1.5 on 2023-01-14 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_authhash_created_authhash_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 0, 18, 43, 201824, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 0, 18, 43, 199773, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
