# Generated by Django 4.1.5 on 2023-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_authhash_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
