# Generated by Django 4.1.5 on 2023-01-13 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_student_telegram_username_alter_authhash_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authhash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 0, 22, 16, 294367, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 0, 22, 16, 294791, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
