# Generated by Django 4.1.5 on 2023-01-24 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examsubject', verbose_name='экзамен')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source', verbose_name='источник')),
            ],
            options={
                'verbose_name': 'источник для экзаменов',
                'verbose_name_plural': 'источники для экзаменов',
                'unique_together': {('exam', 'source')},
            },
        ),
    ]
