# Generated by Django 4.1.5 on 2023-01-26 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_courscustomer_curator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexam',
            options={'ordering': ['-task__created_at'], 'verbose_name': 'задание по экзамену', 'verbose_name_plural': 'задания по экзаменам'},
        ),
        migrations.AlterField(
            model_name='courscustomer',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_customers', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='courscustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_courses', to=settings.AUTH_USER_MODEL, verbose_name='ученик'),
        ),
        migrations.AlterField(
            model_name='taskexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examsubject', verbose_name='экзамен'),
        ),
        migrations.AlterField(
            model_name='taskexam',
            name='kim_number',
            field=models.CharField(default='', max_length=5, verbose_name='Номер КИМ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskexam',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.task', verbose_name='задание'),
        ),
    ]
