# Generated by Django 4.1.5 on 2023-01-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_examsubject_kim_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Test task', max_length=128, verbose_name='название задания'),
            preserve_default=False,
        ),
    ]
