# Generated by Django 4.1.5 on 2023-01-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='cours',
        ),
        migrations.CreateModel(
            name='CoursHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cours', verbose_name='курс')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.homework', verbose_name='домашнее задание')),
            ],
            options={
                'verbose_name': 'ДЗ курса',
                'verbose_name_plural': 'ДЗ курса',
            },
        ),
    ]
