# Generated by Django 4.1.5 on 2023-01-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_homework_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='cours',
        ),
    ]
