# Generated by Django 4.1.5 on 2023-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_homework_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='courshomework',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дедлайн'),
        ),
    ]
