# Generated by Django 4.1.5 on 2023-01-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_courshomework_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='tasks',
            field=models.ManyToManyField(through='api.HomeworkTask', to='api.taskexam', verbose_name='задания'),
        ),
    ]
