# Generated by Django 4.1.5 on 2023-01-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_usersolution_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_files_urls',
            field=models.JSONField(blank=True, null=True, verbose_name='ссылки на файлы для задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_image_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ссылка на условие задания'),
        ),
    ]
